export const mapData = [
  {
    col_ID: -4,
    data: [
      { x: -4, y: -3, label: "", terrain: "", notes: "" },
      { x: -4, y: -2, label: "Sumpf (Untote)", terrain: "swamp", notes: "" },
      {
        x: -4,
        y: -1,
        label: "Zentauren-<br/>Paar",
        terrain: "steppe",
        notes: "",
      },
      { x: -4, y: 0, label: "Wasserfall", terrain: "steppe", notes: "" },
      { x: -4, y: 1, label: "", terrain: "", notes: "" },
      { x: -4, y: 2, label: "", terrain: "", notes: "" },
      { x: -4, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: -3,
    data: [
      {
        x: -3,
        y: -3,
        label: "Steinwald (Geister),<br/>Riss",
        terrain: "forest",
        notes: "",
      },
      {
        x: -3,
        y: -2,
        label: "<em>Sova</em>",
        terrain: "steppe",
        notes: "",
      },
      { x: -3, y: -1, label: "", terrain: "", notes: "" },
      { x: -3, y: 0, label: "Arena", terrain: "steppe", notes: "" },
      { x: -3, y: 1, label: "", terrain: "", notes: "" },
      { x: -3, y: 2, label: "", terrain: "", notes: "" },
      { x: -3, y: 3, label: "Tränensee", terrain: "water", notes: "" },
    ],
  },
  {
    col_ID: -2,
    data: [
      { x: -2, y: -3, label: "", terrain: "", notes: "" },
      { x: -2, y: -2, label: "", terrain: "", notes: "" },
      { x: -2, y: -1, label: "", terrain: "", notes: "" },
      { x: -2, y: 0, label: "", terrain: "", notes: "" },
      { x: -2, y: 1, label: "", terrain: "hills", notes: "" },
      { x: -2, y: 2, label: "", terrain: "forest", notes: "" },
      { x: -2, y: 3, label: "<em>Pira</em>", terrain: "mountains", notes: "" },
    ],
  },
  {
    col_ID: -1,
    data: [
      { x: -1, y: -3, label: "", terrain: "", notes: "" },
      { x: -1, y: -2, label: "", terrain: "", notes: "" },
      { x: -1, y: -1, label: "", terrain: "", notes: "" },
      { x: -1, y: 0, label: "", terrain: "", notes: "" },
      {
        x: -1,
        y: 1,
        label: "Torfabbau, Frostmoor",
        terrain: "grass",
        notes: "",
      },
      {
        x: -1,
        y: 2,
        label: "<em>Phandalin</em>",
        terrain: "forest",
        notes: "",
      },
      { x: -1, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: 0,
    data: [
      { x: 0, y: -3, label: "", terrain: "", notes: "" },
      { x: 0, y: -2, label: "", terrain: "", notes: "" },
      { x: 0, y: -1, label: "", terrain: "", notes: "" },
      {
        x: 0,
        y: 0,
        label: "<em>Mythea</em>",
        terrain: "city",
        notes: "",
      },
      { x: 0, y: 1, label: "Köhler, Sägemühle", terrain: "grass", notes: "" },
      { x: 0, y: 2, label: "Frostwald", terrain: "forest", notes: "" },
      { x: 0, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: 1,
    data: [
      { x: 1, y: -3, label: "", terrain: "", notes: "" },
      { x: 1, y: -2, label: "", terrain: "", notes: "" },
      { x: 1, y: -1, label: "", terrain: "" },
      {
        x: 1,
        y: 0,
        label: "Obst- und Olivenhaine",
        terrain: "grass",
        notes: "",
      },
      {
        x: 1,
        y: 1,
        label: "Holzfäller-<br/>Lager, Riss",
        terrain: "forest",
        notes: "",
      },
      { x: 1, y: 2, label: "", terrain: "", notes: "" },
      { x: 1, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: 2,
    data: [
      { x: 2, y: -3, label: "", terrain: "", notes: "" },
      { x: 2, y: -2, label: "", terrain: "", notes: "" },
      { x: 2, y: -1, label: "", terrain: "", notes: "" },
      { x: 2, y: 0, label: "", terrain: "", notes: "" },
      { x: 2, y: 1, label: "", terrain: "", notes: "" },
      { x: 2, y: 2, label: "", terrain: "", notes: "" },
      { x: 2, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: 3,
    data: [
      { x: 3, y: -3, label: "", terrain: "", notes: "" },
      { x: 3, y: -2, label: "", terrain: "", notes: "" },
      { x: 3, y: -1, label: "", terrain: "", notes: "" },
      { x: 3, y: 0, label: "", terrain: "", notes: "" },
      { x: 3, y: 1, label: "", terrain: "", notes: "" },
      { x: 3, y: 2, label: "", terrain: "", notes: "" },
      { x: 3, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: 4,
    data: [
      { x: 4, y: -3, label: "", terrain: "", notes: "" },
      { x: 4, y: -2, label: "", terrain: "", notes: "" },
      { x: 4, y: -1, label: "", terrain: "", notes: "" },
      { x: 4, y: 0, label: "", terrain: "", notes: "" },
      { x: 4, y: 1, label: "", terrain: "", notes: "" },
      { x: 4, y: 2, label: "", terrain: "", notes: "" },
      { x: 4, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: 5,
    data: [
      {
        x: 5,
        y: -3,
        label: "<em>Argos</em>",
        terrain: "capitol",
        notes: "",
      },
      { x: 5, y: -2, label: "", terrain: "", notes: "" },
      { x: 5, y: -1, label: "", terrain: "", notes: "" },
      { x: 5, y: 0, label: "", terrain: "", notes: "" },
      { x: 5, y: 1, label: "", terrain: "", notes: "" },
      { x: 5, y: 2, label: "", terrain: "", notes: "" },
      { x: 5, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
  {
    col_ID: 6,
    data: [
      { x: 6, y: -3, label: "", terrain: "", notes: "" },
      { x: 6, y: -2, label: "", terrain: "", notes: "" },
      { x: 6, y: -1, label: "", terrain: "", notes: "" },
      { x: 6, y: 0, label: "", terrain: "", notes: "" },
      { x: 6, y: 1, label: "", terrain: "", notes: "" },
      { x: 6, y: 2, label: "", terrain: "", notes: "" },
      { x: 6, y: 3, label: "", terrain: "", notes: "" },
    ],
  },
];
